In [24]:
import cv2
import numpy as np
import os
from skimage.feature import hog

In [25]:
# Step 1: Load images
# The images are in a folder called 'Database', and named as img1.jpg, img2.jpg, ..., img10.jpg
image_folder = 'Database'
image_files = [f'img{i}.jpg' for i in range(1, 11)]

# Initialize lists to store feature vectors and labels
features = []
labels = []

In [26]:
# Step 2: Pre-process images and extract features

# Define a fixed image size for resizing (e.g., 128x128)
fixed_size = (128, 128)

# Loop through the images
for idx, file in enumerate(image_files):
    # Load the image
    img_path = os.path.join(image_folder, file)
    image = cv2.imread(img_path)
    
    # Pre-processing step 1: Resize the image to a fixed size
    resized_image = cv2.resize(image, fixed_size)

    # Pre-processing step 1: Convert image to grayscale
    gray_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

    # Pre-processing step 2: Apply Histogram Equalization
    equalized_image = cv2.equalizeHist(gray_image)
    
    #step 3: HOG
    # Feature Extraction: Histogram of Oriented Gradients (HOG)
    # HOG captures gradients/edges for each small region of the image, which helps in object detection (in this case, face features).
    # Parameters for HOG (we use a small cell size to capture finer details in faces)
    fd, hog_image = hog(equalized_image, orientations=8, pixels_per_cell=(8, 8), 
                        cells_per_block=(2, 2), block_norm='L2-Hys', visualize=True)
    
    # Append the extracted feature vector and label
    features.append(fd)
    labels.append(idx)  # Assuming each image has a unique label 0-9

In [27]:
# Step 4: Create matrices A and B
Matrix_A = np.array(features)  # Matrix A: feature vectors from HOG
Matrix_B = np.array(labels)    # Matrix B: corresponding labels

# Print Matrix A (feature vectors) and Matrix B (labels)
print("Matrix A (Feature Vectors):")
print(Matrix_A)

print("\nMatrix B (Labels):")
print(Matrix_B)

Matrix A (Feature Vectors):
[[0.22213261 0.02759465 0.02759465 ... 0.05022804 0.11607798 0.03519271]
 [0.06952808 0.         0.29635955 ... 0.22787092 0.08655083 0.18601999]
 [0.         0.         0.         ... 0.00326683 0.01920036 0.01988374]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.09923033 0.16644651 0.16813906]
 [0.         0.         0.         ... 0.34497987 0.1107012  0.00996348]]

Matrix B (Labels):
[0 1 2 3 4 5 6 7 8 9]
